# Generated by Django 4.2 on 2026-04-18 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("points", models.IntegerField()),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manuale"),
                            ("wikidata", "Proprietà Wikidata"),
                            ("age", "Formula età"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("wikidata_property", models.CharField(blank=True, max_length=20)),
                ("wikidata_value", models.CharField(blank=True, max_length=20)),
                ("age_formula", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tipo bonus",
                "verbose_name_plural": "Tipi bonus",
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("registration_opens", models.DateField()),
                ("registration_closes", models.DateField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "jolly_month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Gennaio"),
                            (2, "Febbraio"),
                            (3, "Marzo"),
                            (4, "Aprile"),
                            (5, "Maggio"),
                            (6, "Giugno"),
                            (7, "Luglio"),
                            (8, "Agosto"),
                            (9, "Settembre"),
                            (10, "Ottobre"),
                            (11, "Novembre"),
                            (12, "Dicembre"),
                        ],
                        null=True,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="game.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Squadra",
                "verbose_name_plural": "Squadre",
                "ordering": ["name"],
                "unique_together": {("manager", "season")},
            },
        ),
        migrations.CreateModel(
            name="WikipediaPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wikidata_id", models.CharField(max_length=20, unique=True)),
                ("name_it", models.CharField(max_length=300)),
                ("name_en", models.CharField(blank=True, max_length=300)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_year", models.IntegerField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                ("death_year", models.IntegerField(blank=True, null=True)),
                ("is_dead", models.BooleanField(default=False)),
                ("claims_cache", models.JSONField(blank=True, default=dict)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("wikipedia_url_it", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Persona Wikipedia",
                "verbose_name_plural": "Persone Wikipedia",
                "ordering": ["name_it"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_captain", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_members",
                        to="game.wikipediaperson",
                    ),
                ),
                (
                    "replaced_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="game.teammember",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="game.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro squadra",
                "verbose_name_plural": "Membri squadra",
            },
        ),
        migrations.CreateModel(
            name="Death",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("death_date", models.DateField()),
                ("death_age", models.IntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wikidata", "Rilevato da Wikidata"),
                            ("manual", "Inserito manualmente"),
                        ],
                        default="wikidata",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_deaths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="death",
                        to="game.wikipediaperson",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deaths",
                        to="game.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decesso",
                "verbose_name_plural": "Decessi",
                "ordering": ["death_date"],
            },
        ),
        migrations.CreateModel(
            name="DeathBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_awarded", models.IntegerField()),
                ("is_auto_detected", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "bonus_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awarded",
                        to="game.bonustype",
                    ),
                ),
                (
                    "death",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="game.death",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus decesso",
                "verbose_name_plural": "Bonus decesso",
                "unique_together": {("death", "bonus_type")},
            },
        ),
    ]
