# Generated by Django 5.2.13 on 2026-04-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_season_substitution_deadline_days_pushsubscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonustype",
            name="points_formula",
            field=models.CharField(
                blank=True,
                help_text='Formula per punti dinamici, può usare la variabile `age` (es. "3*(60-age)").',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="is_original",
            field=models.BooleanField(
                default=False,
                help_text="Giocata originale: la persona è stata scelta solo da questo manager all'inizio della stagione.",
            ),
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="description_it",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="occupation",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="summary_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="summary_it",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bonustype",
            name="age_formula",
            field=models.CharField(
                blank=True,
                help_text='Condizione che deve essere vera (es. "age < 60").',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bonustype",
            name="detection_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manuale"),
                    ("wikidata", "Proprietà Wikidata"),
                    ("age", "Formula età"),
                    ("original", "Giocata originale"),
                    ("first_death", "Primo decesso della stagione"),
                    ("last_death", "Ultimo decesso della stagione"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bonustype",
            name="points",
            field=models.IntegerField(
                help_text="Punti fissi. Ignorato se points_formula è valorizzato."
            ),
        ),
    ]
