# Generated by Django 5.2.13 on 2026-04-25 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_align_bonuses_with_rulebook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="game.season",
            ),
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            (
                                "public",
                                "Pubblica (visibile a tutti, iscrizione libera)",
                            ),
                            ("private", "Privata (solo su invito o codice)"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        blank=True,
                        help_text="Codice invito per leghe private.",
                        max_length=32,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Inizio del periodo di gioco (decessi che contano)."
                    ),
                ),
                ("end_date", models.DateField(help_text="Fine del periodo di gioco.")),
                ("registration_opens", models.DateField()),
                ("registration_closes", models.DateField()),
                ("max_captains", models.PositiveIntegerField(default=1)),
                (
                    "max_non_captains",
                    models.PositiveIntegerField(
                        default=11, help_text="Numero di morituri non capitano."
                    ),
                ),
                (
                    "jolly_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Se True, ogni squadra può avere un mese jolly.",
                    ),
                ),
                ("base_points", models.PositiveIntegerField(default=50)),
                ("captain_multiplier", models.PositiveSmallIntegerField(default=2)),
                ("jolly_multiplier", models.PositiveSmallIntegerField(default=2)),
                (
                    "substitution_deadline_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Giorni per sostituire un giocatore deceduto.",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, la composizione delle squadre è bloccata.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lega",
                "verbose_name_plural": "Leghe",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="game.league",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("manager", "league")},
        ),
        migrations.CreateModel(
            name="LeagueBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "override_points",
                    models.IntegerField(
                        blank=True,
                        help_text="Punti specifici per questa lega. Se vuoto usa i punti del BonusType.",
                        null=True,
                    ),
                ),
                (
                    "override_formula",
                    models.CharField(
                        blank=True,
                        help_text="Formula punti specifica per la lega (sovrascrive points_formula del BonusType).",
                        max_length=200,
                    ),
                ),
                (
                    "bonus_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_bonuses",
                        to="game.bonustype",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_bonuses",
                        to="game.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus di lega",
                "verbose_name_plural": "Bonus di lega",
                "unique_together": {("league", "bonus_type")},
            },
        ),
        migrations.AddField(
            model_name="league",
            name="bonus_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="leagues",
                through="game.LeagueBonus",
                to="game.bonustype",
            ),
        ),
        migrations.CreateModel(
            name="LeagueMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Amministratore"),
                            ("member", "Membro"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="game.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Iscrizione lega",
                "verbose_name_plural": "Iscrizioni lega",
                "ordering": ["-joined_at"],
                "unique_together": {("league", "user")},
            },
        ),
    ]
