# Generated by Django 5.2.13 on 2026-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_seed_leagues_from_seasons"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wikidata_check_interval_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Ore minime tra un controllo Wikidata e il successivo per ogni giocatore.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impostazioni sito",
                "verbose_name_plural": "Impostazioni sito",
            },
        ),
        migrations.AddField(
            model_name="wikipediaperson",
            name="data_frozen",
            field=models.BooleanField(
                default=False,
                help_text="Se True, escluso dai controlli automatici (solo refresh manuale).",
            ),
        ),
    ]
