# Generated by Django 4.2.30 on 2026-04-26 18:04

from django.db import migrations, models
import django.db.models.deletion


def migrate_dark_mode_to_theme(apps, schema_editor):
    """Mappa dark_mode=True → theme_preference='dark'. False resta 'auto' (default
    del nuovo campo) per dare priorità al tema di sistema."""
    UserProfile = apps.get_model("game", "UserProfile")
    UserProfile.objects.filter(dark_mode=True).update(theme_preference="dark")


def reverse_theme_to_dark_mode(apps, schema_editor):
    UserProfile = apps.get_model("game", "UserProfile")
    UserProfile.objects.filter(theme_preference="dark").update(dark_mode=True)
    UserProfile.objects.exclude(theme_preference="dark").update(dark_mode=False)


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_sitesettings_and_data_frozen"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[
                    ("auto", "Automatico (segue il dispositivo)"),
                    ("light", "Chiaro"),
                    ("dark", "Scuro"),
                ],
                default="auto",
                help_text="Tema dell'interfaccia: automatico segue il dispositivo.",
                max_length=8,
            ),
        ),
        migrations.RunPython(migrate_dark_mode_to_theme, reverse_theme_to_dark_mode),
        migrations.RemoveField(
            model_name="userprofile",
            name="dark_mode",
        ),
        migrations.CreateModel(
            name="SubstitutionReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_days",
                    models.PositiveIntegerField(
                        help_text="Soglia (giorni rimanenti) per cui questo reminder è stato inviato."
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("push_sent", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="game.teammember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder sostituzione",
                "verbose_name_plural": "Reminder sostituzione",
                "indexes": [
                    models.Index(
                        fields=["team_member", "threshold_days"],
                        name="game_substi_team_me_ce52c9_idx",
                    )
                ],
                "unique_together": {("team_member", "threshold_days")},
            },
        ),
    ]
