# Generated by Django 4.2.30 on 2026-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_theme_preference_and_substitution_reminder"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="death",
            index=models.Index(
                fields=["death_date"], name="game_death_death_d_a02c78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="death",
            index=models.Index(
                fields=["is_confirmed", "death_date"],
                name="game_death_is_conf_508c00_idx",
            ),
        ),
    ]
