# Generated by Django 4.2.30 on 2026-05-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_theme_preference_and_substitution_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='search_wikipedia_filter',
            field=models.CharField(choices=[('none', 'Tutti i personaggi Wikidata'), ('itwiki', 'Solo con pagina Wikipedia italiana'), ('enwiki', 'Solo con pagina Wikipedia inglese')], default='none', max_length=10),
        ),
    ]
