# Generated by Django 4.2.30 on 2026-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_league_search_wikipedia_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='search_wikipedia_filter',
        ),
        migrations.AddField(
            model_name='league',
            name='search_wikipedia_langs',
            field=models.TextField(blank=True, default='', help_text='Lingue Wikipedia accettate (es. itwiki,enwiki). Vuoto = tutta Wikidata.'),
        ),
    ]
