# Generated by Django 4.2.30 on 2026-07-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_remove_league_search_wikipedia_filter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="death",
            name="season",
        ),
        migrations.RemoveField(
            model_name="team",
            name="season",
        ),
        migrations.DeleteModel(
            name="Season",
        ),
    ]
