# Generated by Django 4.2.30 on 2026-07-03 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_remove_first_last_death_bonus_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonustype",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_bonus_types",
                to="game.league",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="max_total_age",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Somma massima delle età dei membri attivi di una squadra (0 = nessun limite).",
            ),
        ),
        migrations.AlterField(
            model_name="bonustype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="bonustype",
            unique_together={("league", "name")},
        ),
    ]
