# Generated by Django 5.2.16 on 2026-07-12 15:35

import django.db.models.deletion
import game.models
from django.conf import settings
from django.db import migrations, models


def migrate_notification_prefs_forward(apps, schema_editor):
    """Porta i vecchi booleani push/email nella matrice notification_prefs.

    Le categorie "decessi" e "sostituzione" ereditano i vecchi valori; gli
    eventi lega restano ai default (off) di default_notification_prefs.
    """
    UserProfile = apps.get_model("game", "UserProfile")
    for profile in UserProfile.objects.all():
        push = getattr(profile, "push_notifications_enabled", True)
        email = getattr(profile, "email_notifications_enabled", True)
        prefs = game.models.default_notification_prefs()
        prefs["death"] = {"push": bool(push), "email": bool(email)}
        prefs["substitution"] = {"push": bool(push), "email": bool(email)}
        profile.notification_prefs = prefs
        profile.save(update_fields=["notification_prefs"])


def migrate_notification_prefs_backward(apps, schema_editor):
    """Ripristina i booleani dalla categoria "decessi" della matrice."""
    UserProfile = apps.get_model("game", "UserProfile")
    for profile in UserProfile.objects.all():
        death = (profile.notification_prefs or {}).get("death") or {}
        profile.push_notifications_enabled = bool(death.get("push", True))
        profile.email_notifications_enabled = bool(death.get("email", True))
        profile.save(update_fields=[
            "push_notifications_enabled", "email_notifications_enabled",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_remove_manual_and_olympic_system_bonuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1) Aggiungi la nuova matrice preferenze...
        migrations.AddField(
            model_name="userprofile",
            name="notification_prefs",
            field=models.JSONField(
                default=game.models.default_notification_prefs,
                help_text="Matrice preferenze notifiche: {categoria: {push: bool, email: bool}}. Il feed in-app è sempre attivo e non compare qui.",
            ),
        ),
        # 2) ...popolala dai vecchi booleani (ancora presenti a questo punto)...
        migrations.RunPython(
            migrate_notification_prefs_forward,
            migrate_notification_prefs_backward,
        ),
        # 3) ...poi rimuovi i vecchi booleani.
        migrations.RemoveField(
            model_name="userprofile",
            name="email_notifications_enabled",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="push_notifications_enabled",
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("death", "Decesso"),
                            ("death_team", "Decesso nella tua squadra"),
                            ("substitution_reminder", "Reminder sostituzione"),
                            ("league_joined", "Nuovo iscritto alla lega"),
                            ("league_started", "Lega iniziata"),
                            ("league_ended", "Lega conclusa"),
                            ("team_locked", "Squadra bloccata"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "url",
                    models.CharField(
                        blank=True, help_text="Link relativo al target.", max_length=500
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "death",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="game.death",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="game.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifica",
                "verbose_name_plural": "Notifiche",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="game_notifi_user_id_86205a_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="game_notifi_user_id_7cc9c5_idx",
                    ),
                ],
            },
        ),
    ]
