# Generated by Django 5.2.16 on 2026-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_remove_userprofile_email_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("death", "Decesso"),
                    ("death_team", "Decesso nella tua squadra"),
                    ("substitution_reminder", "Reminder sostituzione"),
                    ("preseason_removed", "Membro rimosso (decesso pre-stagione)"),
                    ("league_joined", "Nuovo iscritto alla lega"),
                    ("league_started", "Lega iniziata"),
                    ("league_ended", "Lega conclusa"),
                    ("team_locked", "Squadra bloccata"),
                ],
                max_length=32,
            ),
        ),
    ]
