# Generated by Django 5.2.16 on 2026-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='captain_succession',
            field=models.CharField(choices=[('substitute', 'Il sostituto eredita la fascia'), ('free', 'Il manager sceglie il nuovo capitano alla sostituzione'), ('none', 'La fascia non viene riassegnata')], default='substitute', help_text='Cosa succede alla fascia di capitano quando il capitano muore.', max_length=12),
        ),
        migrations.AddField(
            model_name='league',
            name='secret_rosters_preseason',
            field=models.BooleanField(default=False, help_text="Se True, prima dell'inizio della lega ogni manager vede solo la propria rosa."),
        ),
    ]
